/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Fenetre.java
 *
 * Created on 15 mars 2013, 15:17:57
 */
package subdivison;

import javax.swing.JRadioButton;

/**
 *
 * @author gervaila
 */
public class Fenetre extends javax.swing.JFrame {

	/** Creates new form Fenetre */
	public Fenetre() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        cornerCuttingRadioButton = new javax.swing.JRadioButton();
        chaikinRadioButton = new javax.swing.JRadioButton();
        fourPointSchemeRadioButton = new javax.swing.JRadioButton();
        splineRadioButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        aSlider = new javax.swing.JSlider();
        aLabel = new javax.swing.JLabel();
        bSlider = new javax.swing.JSlider();
        bLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        aireDeDessin1 = new subdivison.AireDeDessin();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Options");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Fermeture");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Fonction");

        buttonGroup1.add(cornerCuttingRadioButton);
        cornerCuttingRadioButton.setSelected(true);
        cornerCuttingRadioButton.setText("Corner cutting");
        cornerCuttingRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(chaikinRadioButton);
        chaikinRadioButton.setText("Chaikin");
        chaikinRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(fourPointSchemeRadioButton);
        fourPointSchemeRadioButton.setText("4 Point scheme");
        fourPointSchemeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(splineRadioButton);
        splineRadioButton.setText("Spline");
        splineRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Epsilon / A, B");

        aSlider.setValue(25);
        aSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                aSliderStateChanged(evt);
            }
        });

        aLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aLabel.setText("0.25");

        bSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bSliderStateChanged(evt);
            }
        });

        bLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bLabel.setText("0.5");

        jButton1.setText("Tout effacer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCheckBox1)
                        .addComponent(cornerCuttingRadioButton)
                        .addComponent(chaikinRadioButton)
                        .addComponent(fourPointSchemeRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))))
                    .addComponent(splineRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(aSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(aLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(bLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cornerCuttingRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chaikinRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fourPointSchemeRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(splineRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(aLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLabel))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout aireDeDessin1Layout = new javax.swing.GroupLayout(aireDeDessin1);
        aireDeDessin1.setLayout(aireDeDessin1Layout);
        aireDeDessin1Layout.setHorizontalGroup(
            aireDeDessin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        aireDeDessin1Layout.setVerticalGroup(
            aireDeDessin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aireDeDessin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aireDeDessin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
		aireDeDessin1.closedPolygon = jCheckBox1.isSelected();
		aireDeDessin1.calculerCourbe();
		aireDeDessin1.repaint();
	}//GEN-LAST:event_jCheckBox1ActionPerformed

	private void aSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_aSliderStateChanged
		aLabel.setText(Double.toString(getA()));
		aireDeDessin1.a = getA();
		aireDeDessin1.calculerCourbe();
		aireDeDessin1.repaint();
		if (getA() > getB()) {
			setB(getA());
		}
	}//GEN-LAST:event_aSliderStateChanged

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		aireDeDessin1.points.clear();
		aireDeDessin1.calculerCourbe();
		aireDeDessin1.repaint();
	}//GEN-LAST:event_jButton1ActionPerformed

	private void bSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bSliderStateChanged
		bLabel.setText(Double.toString(getB()));
		aireDeDessin1.b = getB();
		aireDeDessin1.calculerCourbe();
		aireDeDessin1.repaint();
		if (getB() < getA()) {
			setA(getB());
		}
	}//GEN-LAST:event_bSliderStateChanged

	private void radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonActionPerformed
		JRadioButton selection = (JRadioButton) evt.getSource();
		if (selection == cornerCuttingRadioButton) {
			aireDeDessin1.setFunction(SubdivisionProg.CORNER);
			aSlider.setEnabled(true);
			aSlider.setMinimum(0);
			bSlider.setEnabled(true);
		} else if (selection == chaikinRadioButton) {
			aireDeDessin1.setFunction(SubdivisionProg.CHAIKIN);
			aSlider.setEnabled(false);
			bSlider.setEnabled(false);
		} else if (selection == fourPointSchemeRadioButton) {
			aireDeDessin1.setFunction(SubdivisionProg.FOURPOINT);
			aSlider.setEnabled(true);
			aSlider.setMinimum(-100);
			bSlider.setEnabled(false);
		} else if (selection == splineRadioButton) {
			aireDeDessin1.setFunction(SubdivisionProg.SPLINE);
			aSlider.setEnabled(false);
			bSlider.setEnabled(false);
		}
		aireDeDessin1.calculerCourbe();
		aireDeDessin1.repaint();
	}//GEN-LAST:event_radioButtonActionPerformed

	private double getA() {
		return (double) aSlider.getValue() / 100.0;
	}

	private double getB() {
		return (double) bSlider.getValue() / 100.0;
	}

	private void setA(double a) {
		aSlider.setValue((int) (a * 100));
	}

	private void setB(double b) {
		bSlider.setValue((int) (b * 100));
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aLabel;
    private javax.swing.JSlider aSlider;
    private subdivison.AireDeDessin aireDeDessin1;
    private javax.swing.JLabel bLabel;
    private javax.swing.JSlider bSlider;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton chaikinRadioButton;
    private javax.swing.JRadioButton cornerCuttingRadioButton;
    private javax.swing.JRadioButton fourPointSchemeRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton splineRadioButton;
    // End of variables declaration//GEN-END:variables
}
